export type Lang = "ar" | "en";

export const content = {
  ar: {
    dir: "rtl",
    lang: "ar",
    companyName: "حلول التوسع لتقنية المعلومات",
    companyNameEn: "Expansion Solutions Information Technology",
    tagline: "شريكك التقني الموثوق",
    nav: {
      about: "من نحن",
      vision: "الرؤية",
      services: "خدماتنا",
      clients: "عملاؤنا",
      contact: "تواصل معنا",
      ideaForm: "قدّم فكرتك",
    },
    hero: {
      headline: "شريكك التقني الموثوق نحو مستقبل رقمي أفضل",
      subheadline:
        "نقدم حلولاً تقنية مبتكرة وشاملة تدعم نمو أعمالك وتحقق أهدافك بفعالية واستدامة",
      cta1: "تواصل معنا",
      cta2: "قدّم فكرتك",
    },
    about: {
      title: "من نحن",
      body: "نحن شركة متخصصة في تقديم حلول تقنية مبتكرة وشاملة، تهدف إلى دعم الأفراد والشركات من خلال خدمات متكاملة تجمع بين الجودة، الابتكار، والتكنولوجيا الحديثة. نسعى إلى تمكين عملائنا من تحقيق أهدافهم بفعالية واستدامة من خلال توفير خدمات وحلول تقنية متميزة مصممة خصيصاً لتلبية احتياجاتهم.",
    },
    vision: {
      title: "رؤيتنا",
      body: "أن نصبح الشريك التقني الرائد في تقديم الحلول الرقمية المبتكرة، وأن نكون الخيار الأول للشركات والأفراد الذين يتطلعون إلى تطوير أعمالهم باستخدام أحدث تقنيات التكنولوجيا.",
    },
    mission: {
      title: "رسالتنا",
      body: "نلتزم بتقديم خدمات تقنية عالية الجودة وحلول متطورة تساعد عملاءنا على تحسين أدائهم، وتبني الابتكار، وتعزيز تنافسيتهم في السوق.",
    },
    values: {
      title: "قيمنا",
      items: [
        { icon: "💡", title: "الابتكار", desc: "نؤمن بالإبداع وتقديم أفكار جديدة لتحسين حلولنا وخدماتنا." },
        { icon: "⭐", title: "الجودة", desc: "نلتزم بتقديم خدمات ذات معايير عالمية تضمن رضا العملاء." },
        { icon: "🔄", title: "المرونة", desc: "نعمل على تكييف حلولنا لتناسب احتياجات وتوقعات عملائنا." },
        { icon: "🤝", title: "النزاهة", desc: "نلتزم بالشفافية والاحترافية في جميع تعاملاتنا." },
        { icon: "🌐", title: "الشراكة", desc: "نؤمن ببناء علاقات طويلة الأمد مع عملائنا لتحقيق أهداف مشتركة." },
      ],
    },
    services: {
      title: "خدماتنا",
      items: [
        {
          icon: "🗄️",
          title: "خدمات تخزين ونقل البيانات",
          points: [
            "نقدم حلولًا متكاملة وآمنة لتخزين البيانات ونقلها باستخدام تقنيات متطورة.",
            "تضمن خدماتنا كفاءة وموثوقية عالية لتأمين وحماية بيانات العملاء.",
          ],
        },
        {
          icon: "💻",
          title: "تطوير وبرمجة التطبيقات",
          points: [
            "تصميم وإنشاء تطبيقات برمجية مبتكرة تلبي احتياجات العملاء المتنوعة.",
            "تطوير تطبيقات اتصالات وحلول برمجية متكاملة لتحسين العمليات اليومية.",
          ],
        },
        {
          icon: "🌐",
          title: "تطوير التطبيقات والمواقع الإلكترونية",
          points: [
            "تصميم وتطوير مواقع إلكترونية متوافقة مع أحدث المعايير لتقديم تجربة استخدام متميزة.",
            "بناء تطبيقات مخصصة على منصات متعددة تركز على تعزيز الكفاءة وتحسين تجربة المستخدم.",
          ],
        },
        {
          icon: "🤖",
          title: "حلول الذكاء الاصطناعي",
          points: [
            "تطوير أنظمة ذكية تعتمد على تقنيات التعلم الآلي لتحليل البيانات واتخاذ القرارات.",
            "تصميم حلول ذكاء اصطناعي مبتكرة لتحسين العمليات التشغيلية وزيادة الإنتاجية.",
          ],
        },
      ],
    },
    clients: {
      title: "عملاؤنا الرئيسيون",
      items: [
        { icon: "🏢", title: "الشركات الصغيرة والمتوسطة", desc: "التي تسعى لتطوير حضورها الرقمي وتحسين كفاءتها التشغيلية." },
        { icon: "🏛️", title: "المؤسسات الكبرى", desc: "التي تحتاج إلى حلول تقنية متقدمة تلبي متطلباتها التشغيلية." },
        { icon: "⚖️", title: "الهيئات الحكومية", desc: "التي تهدف إلى رقمنة خدماتها وتحسين كفاءتها الإدارية." },
        { icon: "🚀", title: "الشركات الناشئة", desc: "التي تبحث عن شريك تقني موثوق لدعم رحلتها في سوق المنافسة." },
      ],
    },
    closing: {
      title: "ختاماً",
      body: "نحن في شركتنا نؤمن بأن التكنولوجيا هي أداة أساسية لتحقيق النجاح. لذلك، نسعى باستمرار لتقديم حلول تقنية متطورة تلبي تطلعات عملائنا وتساعدهم على تحقيق الريادة في مجالاتهم.",
      cta: "ابدأ رحلتك معنا",
    },
    contact: {
      title: "تواصل معنا",
      subtitle: "نحن هنا لمساعدتك. تواصل معنا اليوم.",
      phone: "الهاتف",
      email: "البريد الإلكتروني",
      ideaCta: "ابدأ بإرسال فكرتك",
      emailSubject: "طلب تواصل من الموقع",
    },
    ideaForm: {
      title: "قدّم فكرتك",
      subtitle: "شاركنا فكرتك ومعلومات مشروعك، وسنقوم بمراجعتها لإعداد عرض سعر ومقترح مناسب لاحتياجاتك.",
      emailSubject: "طلب عرض سعر ومقترح مشروع جديد",
      sectionA: "معلومات التواصل",
      sectionB: "معلومات الفكرة والمشروع",
      sectionC: "نوع التقنية المطلوبة",
      sectionD: "نطاق المشروع والتفاصيل التجارية",
      sectionE: "تفاصيل إضافية",
      fields: {
        fullName: "الاسم الكامل",
        email: "البريد الإلكتروني",
        mobile: "رقم الجوال",
        company: "اسم الشركة",
        ideaName: "اسم الفكرة / المشروع",
        startupName: "ما اسم الشركة الناشئة أو المشروع؟",
        ideaDesc: "صف فكرتك باختصار",
        problemSolved: "ما المشكلة التي يحلها المشروع؟",
        targetAudience: "من هو الجمهور المستهدف؟",
        techType: "نوع التقنية المطلوبة",
        hasPrototype: "هل لديك نموذج أولي أو تصميمات؟",
        projectStage: "ما المرحلة الحالية للمشروع؟",
        budget: "الميزانية التقديرية",
        timeline: "الإطار الزمني المتوقع",
        notes: "تفاصيل إضافية",
      },
      placeholders: {
        fullName: "أدخل اسمك الكامل",
        email: "example@email.com",
        mobile: "05xxxxxxxx",
        company: "اسم شركتك (اختياري)",
        ideaName: "اسم مشروعك أو فكرتك",
        startupName: "اسم الشركة الناشئة أو المنتج",
        ideaDesc: "اشرح فكرتك بإيجاز...",
        problemSolved: "ما المشكلة التي يسعى مشروعك لحلها؟",
        targetAudience: "من هم المستخدمون أو العملاء المستهدفون؟",
        notes: "أي تفاصيل إضافية أو ملاحظات تودّ مشاركتها...",
      },
      techOptions: [
        "تطوير تطبيقات الجوال",
        "تطوير مواقع إلكترونية",
        "منتج SaaS",
        "منصة ويب",
        "متجر إلكتروني",
        "لوحة تحكم إدارية",
        "ذكاء اصطناعي",
        "حلول مخصصة",
        "أخرى",
      ],
      prototypeOptions: ["نعم", "لا"],
      stageOptions: [
        "مجرد فكرة",
        "نموذج أولي",
        "مشروع قائم يحتاج تطوير",
        "أبحث عن فريق تقني",
      ],
      budgetOptions: [
        "أقل من 5,000 دولار",
        "5,000 - 15,000 دولار",
        "15,000 - 50,000 دولار",
        "أكثر من 50,000 دولار",
        "أفضل مناقشتها لاحقاً",
      ],
      timelineOptions: [
        "بأسرع وقت",
        "خلال شهر",
        "خلال 2-3 أشهر",
        "أكثر من 3 أشهر",
        "غير محدد بعد",
      ],
      submit: "أرسل فكرتك الآن",
      selectPlaceholder: "— اختر —",
    },
    footer: {
      quickLinks: "روابط سريعة",
      rights: "جميع الحقوق محفوظة",
      copy: "© {year} حلول التوسع لتقنية المعلومات.",
    },
  },
  en: {
    dir: "ltr",
    lang: "en",
    companyName: "Expansion Solutions Information Technology",
    companyNameEn: "حلول التوسع لتقنية المعلومات",
    tagline: "Your Trusted Technology Partner",
    nav: {
      about: "About Us",
      vision: "Vision",
      services: "Services",
      clients: "Clients",
      contact: "Contact Us",
      ideaForm: "Submit Your Idea",
    },
    hero: {
      headline: "Your Trusted Technology Partner for a Better Digital Future",
      subheadline:
        "We deliver innovative and comprehensive technology solutions that support your business growth and achieve your goals effectively and sustainably.",
      cta1: "Contact Us",
      cta2: "Submit Your Idea",
    },
    about: {
      title: "About Us",
      body: "We are a company specializing in providing innovative and comprehensive technology solutions, aimed at supporting individuals and businesses through integrated services that combine quality, innovation, and modern technology. We strive to empower our clients to achieve their goals effectively and sustainably by offering distinguished technology services and solutions designed specifically to meet their needs.",
    },
    vision: {
      title: "Our Vision",
      body: "To become the leading technology partner in delivering innovative digital solutions, and to be the first choice for companies and individuals who aspire to develop their businesses using the latest technology.",
    },
    mission: {
      title: "Our Mission",
      body: "We are committed to providing high-quality technology services and advanced solutions that help our clients improve their performance, embrace innovation, and enhance their competitiveness in the market.",
    },
    values: {
      title: "Our Values",
      items: [
        { icon: "💡", title: "Innovation", desc: "We believe in creativity and bringing new ideas to improve our solutions and services." },
        { icon: "⭐", title: "Quality", desc: "We are committed to delivering services that meet global standards and ensure client satisfaction." },
        { icon: "🔄", title: "Flexibility", desc: "We adapt our solutions to meet the needs and expectations of our clients." },
        { icon: "🤝", title: "Integrity", desc: "We are committed to transparency and professionalism in all our dealings." },
        { icon: "🌐", title: "Partnership", desc: "We believe in building long-term relationships with our clients to achieve shared goals." },
      ],
    },
    services: {
      title: "Our Services",
      items: [
        {
          icon: "🗄️",
          title: "Data Storage & Transfer Services",
          points: [
            "We provide integrated and secure data storage and transfer solutions using advanced technologies.",
            "Our services ensure high efficiency and reliability to secure and protect client data.",
          ],
        },
        {
          icon: "💻",
          title: "Application Development & Programming",
          points: [
            "Design and creation of innovative software applications that meet diverse client needs.",
            "Development of communication applications and integrated software solutions to improve daily operations.",
          ],
        },
        {
          icon: "🌐",
          title: "Web & Application Development",
          points: [
            "Design and development of websites compliant with the latest standards to deliver an outstanding user experience.",
            "Building custom applications on multiple platforms focused on enhancing efficiency and improving user experience.",
          ],
        },
        {
          icon: "🤖",
          title: "Artificial Intelligence Solutions",
          points: [
            "Development of intelligent systems based on machine learning technologies to analyze data and support decision-making.",
            "Design of innovative AI solutions to improve operational processes and increase productivity.",
          ],
        },
      ],
    },
    clients: {
      title: "Our Main Clients",
      items: [
        { icon: "🏢", title: "Small & Medium Enterprises", desc: "Seeking to develop their digital presence and improve their operational efficiency." },
        { icon: "🏛️", title: "Large Corporations", desc: "That need advanced technology solutions to meet their operational requirements." },
        { icon: "⚖️", title: "Government Entities", desc: "Aiming to digitize their services and improve their administrative efficiency." },
        { icon: "🚀", title: "Startups", desc: "Looking for a reliable technology partner to support their journey in a competitive market." },
      ],
    },
    closing: {
      title: "In Closing",
      body: "At our company, we believe that technology is an essential tool for achieving success. Therefore, we continuously strive to provide advanced technology solutions that meet our clients' aspirations and help them achieve leadership in their fields.",
      cta: "Start Your Journey With Us",
    },
    contact: {
      title: "Contact Us",
      subtitle: "We are here to help. Reach out to us today.",
      phone: "Phone",
      email: "Email",
      ideaCta: "Start by Submitting Your Idea",
      emailSubject: "Website Contact Request",
    },
    ideaForm: {
      title: "Submit Your Idea",
      subtitle: "Share your idea and project details with us, and we will review them to prepare a suitable quotation and proposal for your needs.",
      emailSubject: "New Project Quote & Proposal Request",
      sectionA: "Contact Information",
      sectionB: "Idea & Project Information",
      sectionC: "Technology Type Required",
      sectionD: "Project Scope & Business Details",
      sectionE: "Additional Notes",
      fields: {
        fullName: "Full Name",
        email: "Email",
        mobile: "Mobile Number",
        company: "Company Name",
        ideaName: "Idea or Project Name",
        startupName: "What is the startup or project called?",
        ideaDesc: "Briefly describe your idea",
        problemSolved: "What problem does the project solve?",
        targetAudience: "Who is the target audience?",
        techType: "Technology Type Required",
        hasPrototype: "Do you have a prototype or designs?",
        projectStage: "What is the current stage of the project?",
        budget: "Estimated Budget",
        timeline: "Expected Timeline",
        notes: "Additional Notes",
      },
      placeholders: {
        fullName: "Enter your full name",
        email: "example@email.com",
        mobile: "+966xxxxxxxxx",
        company: "Your company name (optional)",
        ideaName: "Your project or idea name",
        startupName: "Startup or product name",
        ideaDesc: "Briefly explain your idea...",
        problemSolved: "What problem does your project aim to solve?",
        targetAudience: "Who are the target users or customers?",
        notes: "Any additional details or notes you'd like to share...",
      },
      techOptions: [
        "Mobile App Development",
        "Website Development",
        "SaaS Product",
        "Web Platform",
        "E-commerce",
        "Admin Dashboard",
        "Artificial Intelligence",
        "Custom Solution",
        "Other",
      ],
      prototypeOptions: ["Yes", "No"],
      stageOptions: [
        "Idea stage",
        "Prototype",
        "Existing project needing development",
        "Looking for a technical team",
      ],
      budgetOptions: [
        "Under $5,000",
        "$5,000 - $15,000",
        "$15,000 - $50,000",
        "Above $50,000",
        "Prefer to discuss later",
      ],
      timelineOptions: [
        "As soon as possible",
        "Within 1 month",
        "Within 2–3 months",
        "More than 3 months",
        "Not decided yet",
      ],
      submit: "Send Your Idea Now",
      selectPlaceholder: "— Select —",
    },
    footer: {
      quickLinks: "Quick Links",
      rights: "All Rights Reserved",
      copy: "© {year} Expansion Solutions Information Technology.",
    },
  },
};

export const PHONE = "+966500800785";
export const EMAIL = "info@expantionsolution.com";
